"""Generate TypeScript constants mirrored from pydantic-ai.

The chat frontend sends a reasoning-effort level that has to match
`pydantic_ai.settings.ThinkingEffort` exactly. Rather than hand-copy the
levels into TS (where they drift silently when pydantic-ai changes), derive
them here and write a generated module the frontend imports.

Run via `pnpm gen:constants`. CI and the pre-commit hook regenerate and fail
on any diff, so the committed output stays in sync with the installed
pydantic-ai version.
"""

from __future__ import annotations

from pathlib import Path
from typing import get_args

from pydantic_ai.settings import ThinkingEffort

# agent/scripts/gen_constants.py -> repo root is two parents up.
_REPO_ROOT = Path(__file__).resolve().parents[2]
_OUT = _REPO_ROOT / 'src' / 'lib' / 'generated' / 'thinking-effort.gen.ts'


def render() -> str:
    levels = get_args(ThinkingEffort)
    items = ', '.join(f"'{level}'" for level in levels)
    return (
        '// AUTOGENERATED from pydantic_ai.settings.ThinkingEffort by agent/scripts/gen_constants.py.\n'
        '// Do not edit by hand. Run `pnpm gen:constants` to regenerate.\n'
        f'export const THINKING_EFFORT_LEVELS = [{items}] as const\n'
        '\n'
        'export type ThinkingEffort = (typeof THINKING_EFFORT_LEVELS)[number]\n'
    )


def main() -> None:
    _OUT.parent.mkdir(parents=True, exist_ok=True)
    _OUT.write_text(render())
    print(f'wrote {_OUT.relative_to(_REPO_ROOT)}')


if __name__ == '__main__':
    main()
